on:
  workflow_call:
    inputs:
      workdir:
        description: 'base dir used during builds. If using monorepo, specify the relative path of the service folder. ex.: ./services/example1'
        required: true
        type: string
      stage:
        description: '"stage" used on sls operations as parameter --stage'
        required: true
        type: string
      artifact-retention:
        description: 'Number of days for retaining the generated artifact. Defaults to 3.'
        default: 3
        required: false
        type: number
      deploy:
        description: 'Whetever to run package "deploy" or not. You need to specify AWS keys as secret then.'
        default: true
        required: false
        type: boolean
      environment:
        description: 'Github environment to attach this job to'
        required: false
        type: string
      environment-url:
        description: 'Github environment url'
        required: false
        type: string
      AWS_DEFAULT_REGION:
        description: 'The AWS region to deploy resources to'
        default: ''
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: false
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: false

jobs:
  package-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.workdir }}

    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.sls-deploy.outputs.environment-url }}

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.workdir }}/package-lock.json

    - name: 'Validate workflow input and secrets'
      run: |
        if [ "$(npm run | grep lint)" == "" ]; then
          echo "Your package.json file must have a script named 'lint'. eg: 'eslint'"
          exit 1
        fi
        
        if [ "$(npm run | grep test)" == "" ]; then
          echo "Your package.json file must have a script named 'test'. eg: 'jest"
          exit 1
        fi
        
        if [ "$(npm run | grep sls:package)" == "" ]; then
          echo "Your package.json file must have a script named 'sls:package'. eg: 'sls package'"
          exit 1
        fi

        if [ "${{ inputs.deploy }}" == "true" ]; then
          if [ "${{ inputs.AWS_DEFAULT_REGION }}" == "" ]; then
            echo "'AWS_DEFAULT_REGION' workflow input is required when deploy=true"
            exit 1
          fi

          if [ "${{ secrets.AWS_ACCESS_KEY_ID }}" == "" ]; then
            echo "'AWS_ACCESS_KEY_ID' workflow secret is required when deploy=true"
            exit 1
          fi

          if [ "${{ secrets.AWS_SECRET_ACCESS_KEY }}" == "" ]; then
            echo "'AWS_SECRET_ACCESS_KEY' workflow secret is required when deploy=true"
            exit 1
          fi
          echo $AWS_SECRET_ACCESS_KEY

          if [ "$(npm run | grep sls:deploy)" == "" ]; then
            echo "Your package.json file must have a script named 'sls:deploy'. eg: 'sls deploy'"
            exit 1
          fi
          
          if [ "$(npm run | grep sls:remove)" == "" ]; then
            echo "Your package.json file must have a script named 'sls:remove'. eg: 'sls remove'"
            exit 1
          fi
        fi

    - name: Run npm install (${{ inputs.workdir }})
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Run serverless package with stage "${{ inputs.stage }}"
      run: npm run sls:package -- --stage ${{ inputs.stage }}

    - name: Upload package to GH artifact
      uses: actions/upload-artifact@v3
      with:
        name: sls-package-${{ inputs.stage }}
        path: ${{ inputs.workdir }}/.serverless/
        retention-days: ${{ inputs.artifact-retention }}
    
    - name: Deploy to AWS
      id: sls-deploy
      run: |
        echo "Running 'npm run sls:deploy -- --stage ${{ inputs.stage }}'"
        RESULT=$(AWS_DEFAULT_REGION=${{ inputs.AWS_DEFAULT_REGION }} AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} npm run sls:deploy -- --stage ${{ inputs.stage }})
        echo $RESULT

        # if environment-url set from input, use it
        if [ "${{ inputs.environment-url }}" != "" ]; then
          echo "Setting environment-url from workflow input"
          echo environment-url=${OUT_URL}
          echo "::set-output name=environment-url::${{ inputs.environment-url }}"
          exit 0
        fi

        # extract URL from sls print results
        OUT_URL=$(sls print | | grep -Eo "environment-url: (http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | head -1)
        if [ "$OUT_URL" != "" ]; then
          echo "Setting environment-url from 'sls print' results"
          echo url=${OUT_URL}
          echo "::set-output name=environment-url::${OUT_URL}"
          exit 0
        fi

        # extract URL from sls deploy results
        OUT_URL=$(echo $RESULT | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | head -1)
        if [ "$OUT_URL" != "" ]; then
          echo "Setting environment-url from 'sls deploy' results"
          echo url=${OUT_URL}
          echo "::set-output name=environment-url::${OUT_URL}"
          exit 0
        fi

      if: ${{ inputs.deploy }}

    - name: Info
      run: npm run info --if-present || true
